<?php

namespace AppBundle\Repository;
use AppBundle\Criteria\IssueCriteria;
use AppBundle\Entity\Project;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository implements BaseRepository
{

    public function countCurrentIssues(Project $project)
    {

    }

    /**
     * @param $criteria
     *
     * @return array<Issue>|array<array>
     ***/
    public function match($criteria)
    {
        /** @var IssueCriteria $criteria */
        $qb = $this->createQueryBuilder('u');

        if ($criteria->version !== null) {
            $this->matchVersion($qb, $criteria);
        }

        if($criteria->version !== null) {
            $this->matchStatus($qb, $criteria);
        }

        return $qb->getQuery()->getResult($criteria->hydrateMode);
    }

    private function matchVersion($qb, IssueCriteria $criteria)
    {
        $qb->andWhere('u.fixVersion = :version')->setParameter('version', $criteria->version);
    }

    private function matchStatus($qb, IssueCriteria $criteria)
    {
        $qb->andWhere('u.status = :status')->setParameter('status', $criteria->status);
    }
}
