<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Version;
use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
    /**
     * Looks in db for version 0.0.1, or return new created
     */
    public function findInitialVersion()
    {
        $v = $this->findOneBy(array('minor' => 0, 'major' => 0, 'revision' => 1));
        if(null !== $v)
            return $v;

        return new Version();
    }
}
