<?php

namespace AppBundle\Repository;

/**
 * WebsiteConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
